{% set name = "lazrs-python" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/lazrs/lazrs-{{ version }}.tar.gz
  sha256: 793359e94eb436b34877b4305570774f9b1bba34c4671238512b80b60456d9ce

build:
  number: 0
  # maturin isn't available on s390x
  skip: true  # [py<39 or s390x]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - cargo-bundle-licenses
    - maturin 0.14.17
    - python
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - lazrs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/lazrs/
  summary: Python bindings for laz-rs
  description: |
    Python bindings for laz-rs
  license: MIT
  license_family: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt
  dev_url: https://github.com/laz-rs/laz-rs-python
  doc_url: https://github.com/laz-rs/laz-rs-python

extra:
  recipe-maintainers:
    - hobu
    - tmontaigu
    - weiji14
