{% set name = "lazrs-python" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/lazrs/lazrs-{{ version }}.tar.gz
  sha256: 70880bea1c08b106c6ff46076a4eb299c2335100d5de73ef39777686932a849b

build:
  number: 0
  # maturin isn't available on s390x
  skip: true  # [s390x]
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    # Without maturin here on win, the build fails with `'ModuleNotFoundError: No module named 'lazrs'`
    - cargo-bundle-licenses  # [win]
    - maturin                # [win]
    - python                 # [win]
  host:
    - cargo-bundle-licenses 0.5.0
    - maturin 1.3.1
    - python
    - pip
    - wheel
  run:
    - python

test:
  imports:
    - lazrs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/lazrs/
  summary: Python bindings for laz-rs
  description: |
    Python bindings for laz-rs
  license: MIT
  license_family: MIT
  license_file:
    - THIRDPARTY.yml
    - LICENSE.txt
  dev_url: https://github.com/laz-rs/laz-rs-python
  doc_url: https://github.com/laz-rs/laz-rs-python

extra:
  recipe-maintainers:
    - hobu
    - tmontaigu
    - weiji14
